name: busme
description: "Offline bus tracking application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  # Библиотека для поддержки Monet (динамические цвета Android 12+)
  dynamic_color: 1.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
